### ISSUE TITLE
I can't download the bridge plugin

### ISSUE THREAD

**Issue by TymekSL** [Defective4/AuthMeProxy#12]
Hello, im on the page https://modrinth.com/plugin/authmeproxy and trying download velocity bridge, when I check 1.20.2 version and paper - it will give me download the main of vleocity version. There is no bridge file ! 
4. "Copy AuthMe-Velocity-Bridge-x.x.jar to all auth servers' plugins folder"

**Comment by Defective4** [comment]
Hi @TymekSL!
I will look into this.
In the meantime try downloading the bridge from Github's [Releases](https://github.com/Defective4/AuthMeProxy/releases/latest). It's the same file as hosted on modrinth

**Comment by TymekSL** [comment]
and?

**Comment by TymekSL** [comment]
ok you closed this as completed but its not completed lol

**Comment by Defective4** [comment]
@TymekSL the issue is indeed completed.
I provided you an alternative download link and I'm trying to sort things out with modrinth
